version: '3.8'

services:
 url-shortener:
  build:
   context: .
  ports:
  - "8000:8000"
  depends_on:
   db:
    condition: service_healthy

 db:
  image: postgres:latest
  container_name: url-shortener-db
  ports:
  - "5432:5432"
  environment:
  - PGUSER=${POSTGRES_USER}
  - POSTGRES_USER=${POSTGRES_USER}
  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  - POSTGRES_DB=${POSTGRES_DB}
  restart: always
  volumes:
    - ./schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  healthcheck:
   test: ["CMD-SHELL", "pg_isready"]
   interval: 8s
   timeout: 5s
   retries: 5
  