version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplePassword

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build:
      context: ..
      dockerfile: app/Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    tty: true
    stdin_open: true